use crate::{
    bus::Bus,
    w65c816::{addressing::AddressingMode, cpu::Cpu, instructions::*},
};
use std::collections::HashMap;

pub struct OpCode {
    pub code: u8,
    pub mnemonic: &'static str,
    pub mode: AddressingMode,
    pub function: for<'a, 'b, 'c> fn(&mut Cpu, &mut Bus, &AddressingMode),
}

impl OpCode {
    fn new(
        code: u8,
        mnemonic: &'static str,
        mode: AddressingMode,
        function: for<'a, 'b, 'c> fn(&mut Cpu, &mut Bus, &AddressingMode),
    ) -> Self {
        OpCode {
            code,
            mnemonic,
            mode,
            function,
        }
    }
}

lazy_static! {
    pub static ref CPU_OP_CODES: Vec<OpCode> = vec![
        OpCode::new(0x69, "ADC", AddressingMode::Immediate, adc),
        OpCode::new(0x65, "ADC", AddressingMode::Direct, adc),
        OpCode::new(0x75, "ADC", AddressingMode::DirectX, adc),
        OpCode::new(0x6d, "ADC", AddressingMode::Absolute, adc),
        OpCode::new(0x7d, "ADC", AddressingMode::AbsoluteX, adc),
        OpCode::new(0x79, "ADC", AddressingMode::AbsoluteY, adc),
        OpCode::new(0x61, "ADC", AddressingMode::IndirectX, adc),
        OpCode::new(0x71, "ADC", AddressingMode::IndirectY, adc),
        OpCode::new(0x6f, "ADC", AddressingMode::AbsoluteLong, adc),
        OpCode::new(0x7f, "ADC", AddressingMode::AbsoluteLongX, adc),
        OpCode::new(0x72, "ADC", AddressingMode::Indirect, adc),
        OpCode::new(0x67, "ADC", AddressingMode::IndirectLong, adc),
        OpCode::new(0x77, "ADC", AddressingMode::IndirectLongY, adc),
        OpCode::new(0x63, "ADC", AddressingMode::StackRelative, adc),
        OpCode::new(0x73, "ADC", AddressingMode::StackRelativeIndirectY, adc),
        OpCode::new(0x29, "AND", AddressingMode::Immediate, and),
        OpCode::new(0x25, "AND", AddressingMode::Direct, and),
        OpCode::new(0x35, "AND", AddressingMode::DirectX, and),
        OpCode::new(0x2d, "AND", AddressingMode::Absolute, and),
        OpCode::new(0x3d, "AND", AddressingMode::AbsoluteX, and),
        OpCode::new(0x39, "AND", AddressingMode::AbsoluteY, and),
        OpCode::new(0x21, "AND", AddressingMode::IndirectX, and),
        OpCode::new(0x31, "AND", AddressingMode::IndirectY, and),
        OpCode::new(0x2f, "AND", AddressingMode::AbsoluteLong, and),
        OpCode::new(0x3f, "AND", AddressingMode::AbsoluteLongX, and),
        OpCode::new(0x32, "AND", AddressingMode::Indirect, and),
        OpCode::new(0x27, "AND", AddressingMode::IndirectLong, and),
        OpCode::new(0x37, "AND", AddressingMode::IndirectLongY, and),
        OpCode::new(0x23, "AND", AddressingMode::StackRelative, and),
        OpCode::new(0x33, "AND", AddressingMode::StackRelativeIndirectY, and),
        OpCode::new(0x0a, "ASL", AddressingMode::Implied, asl_a),
        OpCode::new(0x06, "ASL", AddressingMode::Direct, asl),
        OpCode::new(0x16, "ASL", AddressingMode::DirectX, asl),
        OpCode::new(0x0e, "ASL", AddressingMode::Absolute, asl),
        OpCode::new(0x1e, "ASL", AddressingMode::AbsoluteX, asl),
        OpCode::new(0x90, "BCC", AddressingMode::Relative, bcc),
        OpCode::new(0xb0, "BCS", AddressingMode::Relative, bcs),
        OpCode::new(0xf0, "BEQ", AddressingMode::Relative, beq),
        OpCode::new(0x30, "BMI", AddressingMode::Relative, bmi),
        OpCode::new(0xd0, "BNE", AddressingMode::Relative, bne),
        OpCode::new(0x10, "BPL", AddressingMode::Relative, bpl),
        OpCode::new(0x80, "BRA", AddressingMode::Relative, bra),
        OpCode::new(0x82, "BRL", AddressingMode::RelativeLong, brl),
        OpCode::new(0x50, "BVC", AddressingMode::Relative, bvc),
        OpCode::new(0x70, "BVS", AddressingMode::Relative, bvs),
        OpCode::new(0x24, "BIT", AddressingMode::Direct, bit),
        OpCode::new(0x2c, "BIT", AddressingMode::Absolute, bit),
        OpCode::new(0x89, "BIT", AddressingMode::Immediate, bit),
        OpCode::new(0x34, "BIT", AddressingMode::DirectX, bit),
        OpCode::new(0x3c, "BIT", AddressingMode::AbsoluteX, bit),
        OpCode::new(0x00, "BRK", AddressingMode::Immediate, brk),
        OpCode::new(0x18, "CLC", AddressingMode::Implied, clc),
        OpCode::new(0xd8, "CLD", AddressingMode::Implied, cld),
        OpCode::new(0x58, "CLI", AddressingMode::Implied, cli),
        OpCode::new(0xb8, "CLV", AddressingMode::Implied, clv),
        OpCode::new(0x02, "COP", AddressingMode::Immediate, cop),
        OpCode::new(0xc9, "CMP", AddressingMode::Immediate, cmp),
        OpCode::new(0xc5, "CMP", AddressingMode::Direct, cmp),
        OpCode::new(0xd5, "CMP", AddressingMode::DirectX, cmp),
        OpCode::new(0xcd, "CMP", AddressingMode::Absolute, cmp),
        OpCode::new(0xdd, "CMP", AddressingMode::AbsoluteX, cmp),
        OpCode::new(0xd9, "CMP", AddressingMode::AbsoluteY, cmp),
        OpCode::new(0xc1, "CMP", AddressingMode::IndirectX, cmp),
        OpCode::new(0xd1, "CMP", AddressingMode::IndirectY, cmp),
        OpCode::new(0xcf, "CMP", AddressingMode::AbsoluteLong, cmp),
        OpCode::new(0xdf, "CMP", AddressingMode::AbsoluteLongX, cmp),
        OpCode::new(0xd2, "CMP", AddressingMode::Indirect, cmp),
        OpCode::new(0xc7, "CMP", AddressingMode::IndirectLong, cmp),
        OpCode::new(0xd7, "CMP", AddressingMode::IndirectLongY, cmp),
        OpCode::new(0xc3, "CMP", AddressingMode::StackRelative, cmp),
        OpCode::new(0xd3, "CMP", AddressingMode::StackRelativeIndirectY, cmp),
        OpCode::new(0xe0, "CPX", AddressingMode::Immediate, cpx),
        OpCode::new(0xe4, "CPX", AddressingMode::Direct, cpx),
        OpCode::new(0xec, "CPX", AddressingMode::Absolute, cpx),
        OpCode::new(0xc0, "CPY", AddressingMode::Immediate, cpy),
        OpCode::new(0xc4, "CPY", AddressingMode::Direct, cpy),
        OpCode::new(0xcc, "CPY", AddressingMode::Absolute, cpy),
        OpCode::new(0xc6, "DEC", AddressingMode::Direct, dec),
        OpCode::new(0xd6, "DEC", AddressingMode::DirectX, dec),
        OpCode::new(0xce, "DEC", AddressingMode::Absolute, dec),
        OpCode::new(0xde, "DEC", AddressingMode::AbsoluteX, dec),
        OpCode::new(0x3a, "DEC", AddressingMode::Implied, dec_a),
        OpCode::new(0xca, "DEX", AddressingMode::Implied, dex),
        OpCode::new(0x88, "DEY", AddressingMode::Implied, dey),
        OpCode::new(0x49, "EOR", AddressingMode::Immediate, eor),
        OpCode::new(0x45, "EOR", AddressingMode::Direct, eor),
        OpCode::new(0x55, "EOR", AddressingMode::DirectX, eor),
        OpCode::new(0x4d, "EOR", AddressingMode::Absolute, eor),
        OpCode::new(0x5d, "EOR", AddressingMode::AbsoluteX, eor),
        OpCode::new(0x59, "EOR", AddressingMode::AbsoluteY, eor),
        OpCode::new(0x41, "EOR", AddressingMode::IndirectX, eor),
        OpCode::new(0x51, "EOR", AddressingMode::IndirectY, eor),
        OpCode::new(0x4f, "EOR", AddressingMode::AbsoluteLong, eor),
        OpCode::new(0x5f, "EOR", AddressingMode::AbsoluteLongX, eor),
        OpCode::new(0x52, "EOR", AddressingMode::Indirect, eor),
        OpCode::new(0x47, "EOR", AddressingMode::IndirectLong, eor),
        OpCode::new(0x57, "EOR", AddressingMode::IndirectLongY, eor),
        OpCode::new(0x43, "EOR", AddressingMode::StackRelative, eor),
        OpCode::new(0x53, "EOR", AddressingMode::StackRelativeIndirectY, eor),
        OpCode::new(0xe6, "INC", AddressingMode::Direct, inc),
        OpCode::new(0xf6, "INC", AddressingMode::DirectX, inc),
        OpCode::new(0xee, "INC", AddressingMode::Absolute, inc),
        OpCode::new(0xfe, "INC", AddressingMode::AbsoluteX, inc),
        OpCode::new(0x1a, "INC", AddressingMode::Implied, inc_a),
        OpCode::new(0xe8, "INX", AddressingMode::Implied, inx),
        OpCode::new(0xc8, "INY", AddressingMode::Implied, iny),
        OpCode::new(0xdc, "JML", AddressingMode::AbsoluteIndirectLong, jml),
        OpCode::new(0x4c, "JMP", AddressingMode::AbsoluteJMP, jmp),
        OpCode::new(0x6c, "JMP", AddressingMode::AbsoluteIndirect, jmp),
        OpCode::new(0x7c, "JMP", AddressingMode::AbsoluteIndirectX, jmp),
        OpCode::new(0x5c, "JMP", AddressingMode::AbsoluteLong, jmp),
        OpCode::new(0x22, "JSL", AddressingMode::AbsoluteLongJSL, jsl),
        OpCode::new(0x20, "JSR", AddressingMode::AbsoluteJMP, jsr),
        OpCode::new(0xfc, "JSR", AddressingMode::AbsoluteIndirectX, jsr),
        OpCode::new(0xa9, "LDA", AddressingMode::Immediate, lda),
        OpCode::new(0xa5, "LDA", AddressingMode::Direct, lda),
        OpCode::new(0xb5, "LDA", AddressingMode::DirectX, lda),
        OpCode::new(0xad, "LDA", AddressingMode::Absolute, lda),
        OpCode::new(0xbd, "LDA", AddressingMode::AbsoluteX, lda),
        OpCode::new(0xb9, "LDA", AddressingMode::AbsoluteY, lda),
        OpCode::new(0xa1, "LDA", AddressingMode::IndirectX, lda),
        OpCode::new(0xb1, "LDA", AddressingMode::IndirectY, lda),
        OpCode::new(0xaf, "LDA", AddressingMode::AbsoluteLong, lda),
        OpCode::new(0xbf, "LDA", AddressingMode::AbsoluteLongX, lda),
        OpCode::new(0xb2, "LDA", AddressingMode::Indirect, lda),
        OpCode::new(0xa7, "LDA", AddressingMode::IndirectLong, lda),
        OpCode::new(0xb7, "LDA", AddressingMode::IndirectLongY, lda),
        OpCode::new(0xa3, "LDA", AddressingMode::StackRelative, lda),
        OpCode::new(0xb3, "LDA", AddressingMode::StackRelativeIndirectY, lda),
        OpCode::new(0xa2, "LDX", AddressingMode::Immediate, ldx),
        OpCode::new(0xa6, "LDX", AddressingMode::Direct, ldx),
        OpCode::new(0xb6, "LDX", AddressingMode::DirectY, ldx),
        OpCode::new(0xae, "LDX", AddressingMode::Absolute, ldx),
        OpCode::new(0xbe, "LDX", AddressingMode::AbsoluteY, ldx),
        OpCode::new(0xa0, "LDY", AddressingMode::Immediate, ldy),
        OpCode::new(0xa4, "LDY", AddressingMode::Direct, ldy),
        OpCode::new(0xb4, "LDY", AddressingMode::DirectX, ldy),
        OpCode::new(0xac, "LDY", AddressingMode::Absolute, ldy),
        OpCode::new(0xbc, "LDY", AddressingMode::AbsoluteX, ldy),
        OpCode::new(0x4a, "LSR", AddressingMode::Implied, lsr_a),
        OpCode::new(0x46, "LSR", AddressingMode::Direct, lsr),
        OpCode::new(0x56, "LSR", AddressingMode::DirectX, lsr),
        OpCode::new(0x4e, "LSR", AddressingMode::Absolute, lsr),
        OpCode::new(0x5e, "LSR", AddressingMode::AbsoluteX, lsr),
        OpCode::new(0x54, "MVN", AddressingMode::BlockMove, mvn),
        OpCode::new(0x44, "MVP", AddressingMode::BlockMove, mvp),
        OpCode::new(0xea, "NOP", AddressingMode::Implied, nop),
        OpCode::new(0x09, "ORA", AddressingMode::Immediate, ora),
        OpCode::new(0x05, "ORA", AddressingMode::Direct, ora),
        OpCode::new(0x15, "ORA", AddressingMode::DirectX, ora),
        OpCode::new(0x0d, "ORA", AddressingMode::Absolute, ora),
        OpCode::new(0x1d, "ORA", AddressingMode::AbsoluteX, ora),
        OpCode::new(0x19, "ORA", AddressingMode::AbsoluteY, ora),
        OpCode::new(0x01, "ORA", AddressingMode::IndirectX, ora),
        OpCode::new(0x11, "ORA", AddressingMode::IndirectY, ora),
        OpCode::new(0x0f, "ORA", AddressingMode::AbsoluteLong, ora),
        OpCode::new(0x1f, "ORA", AddressingMode::AbsoluteLongX, ora),
        OpCode::new(0x12, "ORA", AddressingMode::Indirect, ora),
        OpCode::new(0x07, "ORA", AddressingMode::IndirectLong, ora),
        OpCode::new(0x17, "ORA", AddressingMode::IndirectLongY, ora),
        OpCode::new(0x03, "ORA", AddressingMode::StackRelative, ora),
        OpCode::new(0x13, "ORA", AddressingMode::StackRelativeIndirectY, ora),
        OpCode::new(0xf4, "PEA", AddressingMode::Immediate, pea),
        OpCode::new(0xd4, "PEI", AddressingMode::StackPEI, pei),
        OpCode::new(0x62, "PER", AddressingMode::Implied, per),
        OpCode::new(0x48, "PHA", AddressingMode::Implied, pha),
        OpCode::new(0x8b, "PHB", AddressingMode::Implied, phb),
        OpCode::new(0x0b, "PHD", AddressingMode::Implied, phd),
        OpCode::new(0x4b, "PHK", AddressingMode::Implied, phk),
        OpCode::new(0x08, "PHP", AddressingMode::Implied, php),
        OpCode::new(0xda, "PHX", AddressingMode::Implied, phx),
        OpCode::new(0x5a, "PHY", AddressingMode::Implied, phy),
        OpCode::new(0x68, "PLA", AddressingMode::Implied, pla),
        OpCode::new(0xab, "PLB", AddressingMode::Implied, plb),
        OpCode::new(0x2b, "PLD", AddressingMode::Implied, pld),
        OpCode::new(0x28, "PLP", AddressingMode::Implied, plp),
        OpCode::new(0xfa, "PLX", AddressingMode::Implied, plx),
        OpCode::new(0x7a, "PLY", AddressingMode::Implied, ply),
        OpCode::new(0xc2, "REP", AddressingMode::Immediate, rep),
        OpCode::new(0x2a, "ROL", AddressingMode::Implied, rol_a),
        OpCode::new(0x26, "ROL", AddressingMode::Direct, rol),
        OpCode::new(0x36, "ROL", AddressingMode::DirectX, rol),
        OpCode::new(0x2e, "ROL", AddressingMode::Absolute, rol),
        OpCode::new(0x3e, "ROL", AddressingMode::AbsoluteX, rol),
        OpCode::new(0x6a, "ROR", AddressingMode::Implied, ror_a),
        OpCode::new(0x66, "ROR", AddressingMode::Direct, ror),
        OpCode::new(0x76, "ROR", AddressingMode::DirectX, ror),
        OpCode::new(0x6e, "ROR", AddressingMode::Absolute, ror),
        OpCode::new(0x7e, "ROR", AddressingMode::AbsoluteX, ror),
        OpCode::new(0x40, "RTI", AddressingMode::Implied, rti),
        OpCode::new(0x6b, "RTL", AddressingMode::Implied, rtl),
        OpCode::new(0x60, "RTS", AddressingMode::Implied, rts),
        OpCode::new(0xe9, "SBC", AddressingMode::Immediate, sbc),
        OpCode::new(0xe5, "SBC", AddressingMode::Direct, sbc),
        OpCode::new(0xf5, "SBC", AddressingMode::DirectX, sbc),
        OpCode::new(0xed, "SBC", AddressingMode::Absolute, sbc),
        OpCode::new(0xfd, "SBC", AddressingMode::AbsoluteX, sbc),
        OpCode::new(0xf9, "SBC", AddressingMode::AbsoluteY, sbc),
        OpCode::new(0xe1, "SBC", AddressingMode::IndirectX, sbc),
        OpCode::new(0xf1, "SBC", AddressingMode::IndirectY, sbc),
        OpCode::new(0xef, "SBC", AddressingMode::AbsoluteLong, sbc),
        OpCode::new(0xff, "SBC", AddressingMode::AbsoluteLongX, sbc),
        OpCode::new(0xf2, "SBC", AddressingMode::Indirect, sbc),
        OpCode::new(0xe7, "SBC", AddressingMode::IndirectLong, sbc),
        OpCode::new(0xf7, "SBC", AddressingMode::IndirectLongY, sbc),
        OpCode::new(0xe3, "SBC", AddressingMode::StackRelative, sbc),
        OpCode::new(0xf3, "SBC", AddressingMode::StackRelativeIndirectY, sbc),
        OpCode::new(0x38, "SEC", AddressingMode::Implied, sec),
        OpCode::new(0xf8, "SED", AddressingMode::Implied, sed),
        OpCode::new(0x78, "SEI", AddressingMode::Implied, sei),
        OpCode::new(0xe2, "SEP", AddressingMode::Immediate, sep),
        OpCode::new(0x85, "STA", AddressingMode::Direct, sta),
        OpCode::new(0x95, "STA", AddressingMode::DirectX, sta),
        OpCode::new(0x8d, "STA", AddressingMode::Absolute, sta),
        OpCode::new(0x9d, "STA", AddressingMode::AbsoluteX, sta),
        OpCode::new(0x99, "STA", AddressingMode::AbsoluteY, sta),
        OpCode::new(0x81, "STA", AddressingMode::IndirectX, sta),
        OpCode::new(0x91, "STA", AddressingMode::IndirectY, sta),
        OpCode::new(0x8f, "STA", AddressingMode::AbsoluteLong, sta),
        OpCode::new(0x9f, "STA", AddressingMode::AbsoluteLongX, sta),
        OpCode::new(0x92, "STA", AddressingMode::Indirect, sta),
        OpCode::new(0x87, "STA", AddressingMode::IndirectLong, sta),
        OpCode::new(0x97, "STA", AddressingMode::IndirectLongY, sta),
        OpCode::new(0x83, "STA", AddressingMode::StackRelative, sta),
        OpCode::new(0x93, "STA", AddressingMode::StackRelativeIndirectY, sta),
        OpCode::new(0x86, "STX", AddressingMode::Direct, stx),
        OpCode::new(0x96, "STX", AddressingMode::DirectY, stx),
        OpCode::new(0x8e, "STX", AddressingMode::Absolute, stx),
        OpCode::new(0x84, "STY", AddressingMode::Direct, sty),
        OpCode::new(0x94, "STY", AddressingMode::DirectX, sty),
        OpCode::new(0x8c, "STY", AddressingMode::Absolute, sty),
        OpCode::new(0x9c, "STZ", AddressingMode::Absolute, stz),
        OpCode::new(0x9e, "STZ", AddressingMode::AbsoluteX, stz),
        OpCode::new(0x64, "STZ", AddressingMode::Direct, stz),
        OpCode::new(0x74, "STZ", AddressingMode::DirectX, stz),
        OpCode::new(0xdb, "STP", AddressingMode::Implied, stp),
        OpCode::new(0xaa, "TAX", AddressingMode::Implied, tax),
        OpCode::new(0xa8, "TAY", AddressingMode::Implied, tay),
        OpCode::new(0x5b, "TCD", AddressingMode::Implied, tcd),
        OpCode::new(0x1b, "TCS", AddressingMode::Implied, tcs),
        OpCode::new(0x7b, "TDC", AddressingMode::Implied, tdc),
        OpCode::new(0x3b, "TSC", AddressingMode::Implied, tsc),
        OpCode::new(0xba, "TSX", AddressingMode::Implied, tsx),
        OpCode::new(0x8a, "TXA", AddressingMode::Implied, txa),
        OpCode::new(0x9a, "TXS", AddressingMode::Implied, txs),
        OpCode::new(0x98, "TYA", AddressingMode::Implied, tya),
        OpCode::new(0x9b, "TXY", AddressingMode::Implied, txy),
        OpCode::new(0xbb, "TYX", AddressingMode::Implied, tyx),
        OpCode::new(0x1c, "TRB", AddressingMode::Absolute, trb),
        OpCode::new(0x14, "TRB", AddressingMode::Direct, trb),
        OpCode::new(0x0c, "TSB", AddressingMode::Absolute, tsb),
        OpCode::new(0x04, "TSB", AddressingMode::Direct, tsb),
        OpCode::new(0xcb, "WAI", AddressingMode::Implied, wai),
        OpCode::new(0x42, "WDM", AddressingMode::Immediate, wdm),
        OpCode::new(0xeb, "XBA", AddressingMode::Implied, xba),
        OpCode::new(0xfb, "XCE", AddressingMode::Implied, xce),
    ];
    pub static ref OPCODES_MAP: HashMap<u8, &'static OpCode> = {
        let mut map = HashMap::new();
        for op in &*CPU_OP_CODES {
            map.insert(op.code, op);
        }
        map
    };
}
